In [ ]:
import  numpy as np 
list = [1, 2, 3, 4, 5]
array = np.array(list)
print(f"array is {array}")
print(f"list is {list}")

array is [1 2 3 4 5]
list is [1, 2, 3, 4, 5]


In [3]:
print(type(array))  
print(type(list))   

<class 'numpy.ndarray'>
<class 'list'>


In [5]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
list3 = [11, 12, 13, 14, 15]  # This list is not used in the multi_array example
multi_array = np.array([list1, list2, list3])  # Only use lists of the same length
print(f"multi_array is {multi_array}")
print(f"multi_array shape is {multi_array.shape}")

multi_array is [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
multi_array shape is (3, 5)


In [6]:
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([6.5, 7.5, 8.5, 9.5, 10.5])
print(f"the dtype of array_1 is {array_1.dtype}")
print(f"the dtype of array_2 is {array_2.dtype}")

the dtype of array_1 is int64
the dtype of array_2 is float64


In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype="U1") 
print("array:", arr)

array: ['1' '2' '3' '4' '5']


In [11]:
students = "noman Ahmed"
student2 = "Ali Khan 707 kamalia"
arr = np.fromiter(students, dtype='U2')
arr2 = np.fromiter(student2, dtype='U2')
print("fromiter() array is: ", arr)
print("fromiter() array2 is: ", arr2)


fromiter() array is:  ['n' 'o' 'm' 'a' 'n' ' ' 'A' 'h' 'm' 'e' 'd']
fromiter() array2 is:  ['A' 'l' 'i' ' ' 'K' 'h' 'a' 'n' ' ' '7' '0' '7' ' ' 'k' 'a' 'm' 'a' 'l'
 'i' 'a']


In [21]:
array_3 = np.arange(1, 20, 2, dtype=float)  # Create an array with values from 1 to 9 with a step of 2
print(f"array_3 is {array_3} dtyps is {array_3.dtype}")

array_3 is [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.] dtyps is float64


In [32]:
array_5 = np.linspace(1, 20,3 )  # Create an array with 5 evenly spaced values between 1 and 10
print(f"array_5 is {array_5} dtyps is {array_5.dtype}")

array_5 is [ 1.  10.5 20. ] dtyps is float64


In [41]:
array6 = np.empty((5, 3), dtype=int, order="f")  # Create an empty array with shape (5, 3)
print(array6)

[[           0            0            0]
 [           0            0            0]
 [           0            0            0]
 [           0            0            0]
 [           0            0 498222825472]]


In [50]:
array7 = np.zeros((3, 4), dtype=int, order='c')  # Create an array filled with zeros with shape (3, 4)

In [51]:
print(f"array7 is {array7} dtyps is {array7.dtype}")

array7 is [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] dtyps is int64


In [53]:
array7 = np.ones((3, 4), dtype=int, order="f")  # Create an array filled with zeros with shape (3, 4)
print(f"array7 is {array7} dtyps is {array7.dtype}")

array7 is [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] dtyps is int64


In [55]:
array8 = [12,3,1,7,4,8,4]
array8 = np.sort(array8)
print(f"sorted array8 is {array8}")

sorted array8 is [ 1  3  4  4  7  8 12]


In [56]:
array8 = [12,3,1,7,4,8,4]
array8 = np.argsort(array8)
print(f"sorted array8 is {array8}")

sorted array8 is [2 1 6 4 3 5 0]


In [57]:
array8 = [12,3,1,7,4,8,4]
array8 = np.lexsort(array8)
print(f"sorted array8 is {array8}")

sorted array8 is 0


In [59]:
array1 = [1, 2, 3, 4, 5]
array2 = [6, 7, 8, 9, 10]
np.concatenate((array1, array2))  # Concatenate two arrays

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim  # Get the number of dimensions of the array

3

In [61]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.shape  # Get the number of dimensions of the array

(3, 2, 4)

In [62]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.size  # Get the number of dimensions of the array

24

In [63]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [67]:
reshape_array = a.reshape(2, 3)  # Reshape the array to 2 rows and 3 columns
print(f"reshape_array is {reshape_array}")

reshape_array is [[0 1 2]
 [3 4 5]]


In [68]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [70]:
data = np.array([1, 2, 3])

data[1]

np.int64(2)

In [71]:

data[0:2]


array([1, 2])

In [72]:

data[1:]


array([2, 3])

In [74]:
array9 = np.array([1, 2, 3, 4, 5, 6])
array9.min()

np.int64(1)

In [75]:
array9 = np.array([1, 2, 3, 4, 5, 6])
array9.max()

np.int64(6)

In [76]:
array9 = np.array([1, 2, 3, 4, 5, 6])
array9.sum()

np.int64(21)

In [80]:
array9 = np.array([1, 2, 3, 4, 5, 6])
np.unique(array9)

array([1, 2, 3, 4, 5, 6])

In [82]:
array9 = np.array([1, 2, 3, 4, 5, 6])
np.reshape(array9, (3, 2))  # Reshape the array to 3 rows and 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [83]:
array9 = np.array([1, 2, 3, 4, 5, 6])
np.flip(array9)

array([6, 5, 4, 3, 2, 1])

In [88]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [89]:
np.save('my_array.npy', x)  # Save the array to a file

In [90]:
b = np.load('my_array.npy')  # Load the array from the file

In [91]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('my_array.csv', csv_arr, delimiter=',')  # Save the array to a CSV file

In [93]:
np.loadtxt('my_array.csv', delimiter=',')  # Load the array from the CSV file



array([1., 2., 3., 4., 5., 6., 7., 8.])